// <auto-generated />
using System;
using Eagency.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Eagency.Dal.Migrations
{
    [DbContext(typeof(EagencyDbContext))]
    [Migration("20210507151517_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Eagency.Dal.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Answer")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTimeOffset(new DateTime(2021, 5, 30, 17, 15, 17, 412, DateTimeKind.Unspecified).AddTicks(557), new TimeSpan(0, 2, 0, 0, 0)),
                            PropertyId = 1,
                            Question = "Are there any shops nearby?",
                            UserId = "seedone"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTimeOffset(new DateTime(2021, 5, 30, 17, 15, 17, 414, DateTimeKind.Unspecified).AddTicks(497), new TimeSpan(0, 2, 0, 0, 0)),
                            PropertyId = 2,
                            Question = "Is the home in a flood zone or prone to other natural disasters?",
                            UserId = "seedtwo"
                        },
                        new
                        {
                            Id = 3,
                            Answer = "He has a new job in another town.",
                            Date = new DateTimeOffset(new DateTime(2021, 5, 30, 17, 15, 17, 414, DateTimeKind.Unspecified).AddTicks(524), new TimeSpan(0, 2, 0, 0, 0)),
                            PropertyId = 3,
                            Question = "Why is the seller leaving?",
                            UserId = "seedthree"
                        },
                        new
                        {
                            Id = 4,
                            Answer = "It's one year old.",
                            Date = new DateTimeOffset(new DateTime(2021, 5, 30, 17, 15, 17, 414, DateTimeKind.Unspecified).AddTicks(530), new TimeSpan(0, 2, 0, 0, 0)),
                            PropertyId = 4,
                            Question = "How old is the roof?",
                            UserId = "seedone"
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTimeOffset(new DateTime(2021, 5, 30, 17, 15, 17, 414, DateTimeKind.Unspecified).AddTicks(534), new TimeSpan(0, 2, 0, 0, 0)),
                            PropertyId = 5,
                            Question = "Is the home in a flood zone or prone to other natural disasters?",
                            UserId = "seedtwo"
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTimeOffset(new DateTime(2021, 5, 30, 17, 15, 17, 414, DateTimeKind.Unspecified).AddTicks(538), new TimeSpan(0, 2, 0, 0, 0)),
                            PropertyId = 6,
                            Question = "How is the neighborhood?",
                            UserId = "seedthree"
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTimeOffset(new DateTime(2021, 5, 30, 17, 15, 17, 414, DateTimeKind.Unspecified).AddTicks(542), new TimeSpan(0, 2, 0, 0, 0)),
                            PropertyId = 7,
                            Question = "Have there been previous problems with the house, or repairs which have been necessary?",
                            UserId = "seedone"
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTimeOffset(new DateTime(2021, 5, 30, 17, 15, 17, 414, DateTimeKind.Unspecified).AddTicks(546), new TimeSpan(0, 2, 0, 0, 0)),
                            PropertyId = 8,
                            Question = "What’s included with the sale?",
                            UserId = "seedtwo"
                        },
                        new
                        {
                            Id = 9,
                            Answer = "He has a new job in another town.",
                            Date = new DateTimeOffset(new DateTime(2021, 5, 30, 17, 15, 17, 414, DateTimeKind.Unspecified).AddTicks(550), new TimeSpan(0, 2, 0, 0, 0)),
                            PropertyId = 1,
                            Question = "Why is the seller leaving?",
                            UserId = "seedthree"
                        },
                        new
                        {
                            Id = 10,
                            Answer = "It's one year old.",
                            Date = new DateTimeOffset(new DateTime(2021, 5, 30, 17, 15, 17, 414, DateTimeKind.Unspecified).AddTicks(554), new TimeSpan(0, 2, 0, 0, 0)),
                            PropertyId = 2,
                            Question = "How old is the roof?",
                            UserId = "seedone"
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTimeOffset(new DateTime(2021, 5, 30, 17, 15, 17, 414, DateTimeKind.Unspecified).AddTicks(558), new TimeSpan(0, 2, 0, 0, 0)),
                            PropertyId = 3,
                            Question = "Is the home in a flood zone or prone to other natural disasters?",
                            UserId = "seedtwo"
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTimeOffset(new DateTime(2021, 5, 30, 17, 15, 17, 414, DateTimeKind.Unspecified).AddTicks(561), new TimeSpan(0, 2, 0, 0, 0)),
                            PropertyId = 6,
                            Question = "How is the neighborhood?",
                            UserId = "seedthree"
                        });
                });

            modelBuilder.Entity("Eagency.Dal.Entities.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClientId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("FeePercentage")
                        .HasColumnType("float");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSigned")
                        .HasColumnType("bit");

                    b.Property<int>("PaymentFrequency")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("PropertyId")
                        .IsUnique();

                    b.ToTable("Contracts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = "seedone",
                            Date = new DateTimeOffset(new DateTime(2021, 5, 20, 17, 15, 17, 414, DateTimeKind.Unspecified).AddTicks(4014), new TimeSpan(0, 2, 0, 0, 0)),
                            FeePercentage = 0.28000000000000003,
                            IsPaid = false,
                            IsSigned = false,
                            PaymentFrequency = 2,
                            PaymentMethod = "BankTransfer",
                            PropertyId = 3
                        },
                        new
                        {
                            Id = 2,
                            ClientId = "seedtwo",
                            Date = new DateTimeOffset(new DateTime(2021, 5, 12, 17, 15, 17, 414, DateTimeKind.Unspecified).AddTicks(5734), new TimeSpan(0, 2, 0, 0, 0)),
                            FeePercentage = 0.57999999999999996,
                            IsPaid = true,
                            IsSigned = true,
                            PaymentFrequency = 3,
                            PaymentMethod = "Cash",
                            PropertyId = 5
                        },
                        new
                        {
                            Id = 3,
                            ClientId = "seedthree",
                            Date = new DateTimeOffset(new DateTime(2021, 6, 3, 17, 15, 17, 414, DateTimeKind.Unspecified).AddTicks(5749), new TimeSpan(0, 2, 0, 0, 0)),
                            FeePercentage = 0.39000000000000001,
                            IsPaid = true,
                            IsSigned = false,
                            PaymentFrequency = 5,
                            PaymentMethod = "Creditcard",
                            PropertyId = 1
                        });
                });

            modelBuilder.Entity("Eagency.Dal.Entities.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AgentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Area")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<string>("HouseType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFurnished")
                        .HasColumnType("bit");

                    b.Property<int>("NumberOfBathrooms")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfBedrooms")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfGarages")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfParkingSpaces")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<bool>("Sold")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgentId = "admin",
                            Area = 110,
                            Description = "Situated on the first floor we offer a two bedroom apartment offering partial Marina Views. The apartment is within walking distance to Swansea Marina and all the local restaurants and coffee shops, close to the new music arena and town centre. The apartment offers a L shaped hallway leading to lounge with french doors and balcony, master bedroom, bathroom, kitchen and second bedroom and benifits from lift access, recently fitted UPVC windows. and allocated secure underground parking.",
                            HouseType = "Detached",
                            ImageName = "alap1.jpg",
                            IsFurnished = true,
                            NumberOfBathrooms = 1,
                            NumberOfBedrooms = 3,
                            NumberOfGarages = 1,
                            NumberOfParkingSpaces = 2,
                            Price = 22000,
                            Sold = true
                        },
                        new
                        {
                            Id = 2,
                            AgentId = "admin",
                            Area = 320,
                            Description = "Built around a traditional Gower cottage and situated within the welcoming Gower village of Horton you will find the spectacular family home that is Castle Hill Cottage. Sitting at the top of its private drive, this detached family home enjoys incredible views over the most southerly point of Gower with its rugged gorse covered cliffs and dunes; over Port Eynon Bay and its rocky point; over the Bristol Channel across to Ilfracombe in North Devon and, on a clear day, as far to the West as Lundy. In its elevated position it is just paces away from the sandy beach of Horton and within a short walk along the boardwalk to Port Eynon. This well-presented home sits in readiness for its new owners to create new memories.",
                            HouseType = "Apartment",
                            ImageName = "alap2.jpg",
                            IsFurnished = false,
                            NumberOfBathrooms = 2,
                            NumberOfBedrooms = 4,
                            NumberOfGarages = 2,
                            NumberOfParkingSpaces = 1,
                            Price = 35500,
                            Sold = false
                        },
                        new
                        {
                            Id = 3,
                            AgentId = "admin",
                            Area = 35,
                            Description = "This very popular and pretty, coastal village of Horton is nestled between the glorious Oxwich Bay and Port Eynon Bay along the South coast of the Gower Peninsula. A popular beach side spot, Horton is in an area of outstanding natural beauty which is blessed with many award-winning sandy beaches and amazing coastal walks.",
                            HouseType = "Mediterranean",
                            ImageName = "alap3.jpg",
                            IsFurnished = true,
                            NumberOfBathrooms = 1,
                            NumberOfBedrooms = 2,
                            NumberOfGarages = 2,
                            NumberOfParkingSpaces = 2,
                            Price = 17400,
                            Sold = true
                        },
                        new
                        {
                            Id = 4,
                            AgentId = "admin",
                            Area = 135,
                            Description = "A three bedroom mid-terrace property within the popular Swansea suburb of Brynhyfryd. Benefiting from being within close proximity to local amenities and approx. 4 miles from Swansea City Centre. The accommodation, benefiting from updating comprises:- Entrance hallway, three reception rooms, kitchen and shower room to the ground floor. To the first floor there are three bedrooms. Externally there is an enclosed rear garden.",
                            HouseType = "Cottage",
                            ImageName = "alap4.jpg",
                            IsFurnished = false,
                            NumberOfBathrooms = 2,
                            NumberOfBedrooms = 4,
                            NumberOfGarages = 0,
                            NumberOfParkingSpaces = 0,
                            Price = 15000,
                            Sold = false
                        },
                        new
                        {
                            Id = 5,
                            AgentId = "admin",
                            Area = 64,
                            Description = "emi detached property comprising entrance hallway, lounge and fitted kitchen to the ground floor. To the first floor there are two bedrooms and a bathroom. Externally there is generously sized garden wrapping around the side and rear. Benefits include uPVC double glazing throughout and newly fitted Hive gas central heating with newly fitted radiators. The property is situated close to local amenities and transport links with easy access to the M4. Viewing is highly recommended to appreciate this well presented property. ",
                            HouseType = "Colonial",
                            ImageName = "alap5.jpg",
                            IsFurnished = false,
                            NumberOfBathrooms = 1,
                            NumberOfBedrooms = 3,
                            NumberOfGarages = 2,
                            NumberOfParkingSpaces = 0,
                            Price = 35000,
                            Sold = true
                        },
                        new
                        {
                            Id = 6,
                            AgentId = "admin",
                            Area = 275,
                            Description = "Light, airy and very nicely presented modern semi detached property situated in a quiet family friendly cul de sac location of Cockett. This well proportioned family home comprises: lounge/ dining room, fitted kitchen and cloakroom to ground floor with three bedrooms and family bathroom to first floor. Benefits: uPVC double glazing, gas central heating, built in storage facilities, two parking spaces and a pleasant enclosed rear garden offering decked seating area, astro turf grass, patio area and side access. Easy access to local amenities, Fforestfach Retail Park, the M4 and Swansea City Centre.",
                            HouseType = "Craftsman",
                            ImageName = "alap6.jpg",
                            IsFurnished = true,
                            NumberOfBathrooms = 3,
                            NumberOfBedrooms = 6,
                            NumberOfGarages = 2,
                            NumberOfParkingSpaces = 1,
                            Price = 45000,
                            Sold = false
                        },
                        new
                        {
                            Id = 7,
                            AgentId = "admin",
                            Area = 75,
                            Description = "A lovely light and airy three bedroom flat within walking distance of local amenities and great school catchments. Briefly comprises: lounge/ dining room, fitted kitchen, three bedrooms, bathroom with separate w/c and communal entrance hallway. This property benefits: uPVC double glazing, gas central heating, small balcony and ample storage facilities. It would make a great home with easy access to Sketty Park, Tycoch Square, Sketty Cross, Singleton Hospital & Park, Killay including Olchfa & Parklands School catchments as well. ",
                            HouseType = "Contemporary",
                            ImageName = "alap7.jpg",
                            IsFurnished = true,
                            NumberOfBathrooms = 1,
                            NumberOfBedrooms = 2,
                            NumberOfGarages = 2,
                            NumberOfParkingSpaces = 1,
                            Price = 32700,
                            Sold = false
                        },
                        new
                        {
                            Id = 8,
                            AgentId = "admin",
                            Area = 110,
                            Description = "Extremely spacious and very well extended detached family home situated in a quiet cul-de-sac at the heart of Cockett. This beautiful property briefly comprises of sitting room, cloakroom/ utility, large open plan L shaped fitted kitchen, dining room and lounge great for modern family living to ground floor, four bedrooms, en-suite, family bathroom to the first floor plus an attic room. The many benefits to this property are uPVC double glazing, gas central heating, off road parking, single garage, enclosed and very well maintained tiered rear garden laid to lawn and patio area. ",
                            HouseType = "Ranch",
                            ImageName = "alap8.jpg",
                            IsFurnished = false,
                            NumberOfBathrooms = 1,
                            NumberOfBedrooms = 2,
                            NumberOfGarages = 1,
                            NumberOfParkingSpaces = 1,
                            Price = 22600,
                            Sold = false
                        });
                });

            modelBuilder.Entity("Eagency.Dal.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "seedone",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "708dfbf9-92d7-47b5-9b54-98080c9aa5fa",
                            Email = "tesztelek@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Teszt",
                            LastName = "Elek",
                            LockoutEnabled = false,
                            NormalizedEmail = "TESZTELEK@GMAIL.COM",
                            NormalizedUserName = "TESZTELEK",
                            PasswordHash = "AQAAAAEAACcQAAAAEBaplIyrKli0OALWfeBiB+owhkri2ibyT0qE16JooD9Z4UO+E4IgT8781/U2rtEVfA==",
                            PhoneNumber = "06/30-152-5123",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5e2084a2-bef7-43d8-967b-67154f09d356",
                            TwoFactorEnabled = false,
                            UserName = "tesztelek"
                        },
                        new
                        {
                            Id = "seedtwo",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1bfaee5f-c965-4287-9ded-5624622f1fa3",
                            Email = "wincheszter@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Winch",
                            LastName = "Eszter",
                            LockoutEnabled = false,
                            NormalizedEmail = "WINCHESZTER@GMAIL.COM",
                            NormalizedUserName = "WINCHESZTER",
                            PasswordHash = "AQAAAAEAACcQAAAAEF84StyoGOvic9QyITNOoGPkGAbJ/bjs+2EV84nPAfWWviRs/jsvvydma19ifCAwCg==",
                            PhoneNumber = "06/30-152-5123",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ba87de8c-eae8-468f-9c9e-3db7a3cd3a1a",
                            TwoFactorEnabled = false,
                            UserName = "wincheszter"
                        },
                        new
                        {
                            Id = "seedthree",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e234276d-1979-4185-8cc5-79faaf600aee",
                            Email = "kbela@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Kis",
                            LastName = "Béla",
                            LockoutEnabled = false,
                            NormalizedEmail = "KBELA@GMAIL.COM",
                            NormalizedUserName = "KBELA",
                            PasswordHash = "AQAAAAEAACcQAAAAEEpvNk2oy5O+blHZpAGQcnUpoozuFZykPXdqp99PQTTlvMROdd7tgYPl657Igih//A==",
                            PhoneNumber = "06/30-152-5123",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "eaea9479-2233-4a9f-bc5a-7ebc10841bfb",
                            TwoFactorEnabled = false,
                            UserName = "kbela"
                        },
                        new
                        {
                            Id = "admin",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e6a8531b-0513-4ac1-92cd-8767678459d5",
                            Email = "admin@eagency.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@EAGENCY.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEEjD98l78UHfgT6OUTMxKlSvlXB6q9fLxtB8GmdGDeGB0f9xc7G+N97HvpqHL8ZnVA==",
                            PhoneNumber = "06/30-152-5123",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "780d894c-408d-4f35-b480-3b1658b216df",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("IdentityServer4.EntityFramework.Entities.DeviceFlowCodes", b =>
                {
                    b.Property<string>("UserCode")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("Expiration")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UserCode");

                    b.HasIndex("DeviceCode")
                        .IsUnique();

                    b.HasIndex("Expiration");

                    b.ToTable("DeviceCodes");
                });

            modelBuilder.Entity("IdentityServer4.EntityFramework.Entities.PersistedGrant", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ConsumedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Key");

                    b.HasIndex("Expiration");

                    b.HasIndex("SubjectId", "ClientId", "Type");

                    b.HasIndex("SubjectId", "SessionId", "Type");

                    b.ToTable("PersistedGrants");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "Agent",
                            ConcurrencyStamp = "404f9f5b-aa16-4478-8b94-dbd58546c5e6",
                            Name = "Agent",
                            NormalizedName = "AGENT"
                        },
                        new
                        {
                            Id = "Customer",
                            ConcurrencyStamp = "6c272d01-c5ad-4ee3-983c-32528d12945a",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "admin",
                            RoleId = "Agent"
                        },
                        new
                        {
                            UserId = "seedone",
                            RoleId = "Customer"
                        },
                        new
                        {
                            UserId = "seedtwo",
                            RoleId = "Customer"
                        },
                        new
                        {
                            UserId = "seedthree",
                            RoleId = "Customer"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Eagency.Dal.Entities.Comment", b =>
                {
                    b.HasOne("Eagency.Dal.Entities.Property", "Property")
                        .WithMany("Comments")
                        .HasForeignKey("PropertyId")
                        .IsRequired();

                    b.HasOne("Eagency.Dal.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId");

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Eagency.Dal.Entities.Contract", b =>
                {
                    b.HasOne("Eagency.Dal.Entities.User", "User")
                        .WithMany("Contracts")
                        .HasForeignKey("ClientId");

                    b.HasOne("Eagency.Dal.Entities.Property", "Property")
                        .WithOne("Contract")
                        .HasForeignKey("Eagency.Dal.Entities.Contract", "PropertyId")
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Eagency.Dal.Entities.Property", b =>
                {
                    b.HasOne("Eagency.Dal.Entities.User", "User")
                        .WithMany("Properties")
                        .HasForeignKey("AgentId");

                    b.OwnsOne("Eagency.Dal.Entities.Address", "Address", b1 =>
                        {
                            b1.Property<int?>("PropertyId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<int>("ZipCode")
                                .HasColumnType("int");

                            b1.HasKey("PropertyId");

                            b1.ToTable("Properties");

                            b1.WithOwner()
                                .HasForeignKey("PropertyId");

                            b1.HasData(
                                new
                                {
                                    PropertyId = 4,
                                    City = "Honolulu",
                                    Country = "USA",
                                    Id = 1,
                                    Street = "Upalu St street 3",
                                    ZipCode = 96705
                                },
                                new
                                {
                                    PropertyId = 3,
                                    City = "Peking",
                                    Country = "China",
                                    Id = 2,
                                    Street = "Chicaego street 45",
                                    ZipCode = 11004
                                },
                                new
                                {
                                    PropertyId = 2,
                                    City = "Madrid",
                                    Country = "Spain",
                                    Id = 3,
                                    Street = "Bueno street 45",
                                    ZipCode = 3424
                                },
                                new
                                {
                                    PropertyId = 1,
                                    City = "New York",
                                    Country = "USA",
                                    Id = 4,
                                    Street = "Pearl street 72",
                                    ZipCode = 5504
                                },
                                new
                                {
                                    PropertyId = 5,
                                    City = "Budapest",
                                    Country = "Hungary",
                                    Id = 5,
                                    Street = "Havanna St street 3",
                                    ZipCode = 1181
                                },
                                new
                                {
                                    PropertyId = 6,
                                    City = "Tokyo",
                                    Country = "Japan",
                                    Id = 6,
                                    Street = "Kaumu street 410",
                                    ZipCode = 5620
                                },
                                new
                                {
                                    PropertyId = 7,
                                    City = "Delhi",
                                    Country = "India",
                                    Id = 7,
                                    Street = "Temple street 80",
                                    ZipCode = 41023
                                },
                                new
                                {
                                    PropertyId = 8,
                                    City = "Shanghai",
                                    Country = "China",
                                    Id = 8,
                                    Street = "Ruraro street 91",
                                    ZipCode = 632302
                                });
                        });

                    b.Navigation("Address");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Eagency.Dal.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Eagency.Dal.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eagency.Dal.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Eagency.Dal.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eagency.Dal.Entities.Property", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("Eagency.Dal.Entities.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Contracts");

                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
